In [53]:
import pandas as pd

In [54]:
df = pd.read_csv("breast_cancer_data.csv")
df.columns = ['Class', 'Age', 'Menopause', 'Tumor-size', 'Inv-nodes', 'Node-caps', 'Deg-malig', 'Breast', 'Breast-quad', 'Irradiat']
df

,Class,Age,Menopause,Tumor-size,Inv-nodes,Node-caps,Deg-malig,Breast,Breast-quad,Irradiat
0,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
2,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
3,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
4,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,left,left_low,no
...,...,...,...,...,...,...,...,...,...,...
280,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
281,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
282,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
283,recurrence-events,40-49,ge40,30-34,3-5,no,3,left,left_low,no
284,recurrence-events,50-59,ge40,30-34,3-5,no,3,left,left_low,no

In [55]:
#Melt
columns_ = ['Class', 'Age', 'Menopause', 'Tumor-size', 'Inv-nodes', 'Node-caps', 'Deg-malig', 'Breast', 'Breast-quad', 'Irradiat']
x = ['Class', 'Age', 'Menopause']

melted_df = pd.melt(df, id_vars = x, var_name= 'Attributes', value_name='Values')
melted_df

                     Class    Age Menopause  Attributes Values
0     no-recurrence-events  40-49   premeno  Tumor-size  20-24
1     no-recurrence-events  40-49   premeno  Tumor-size  20-24
2     no-recurrence-events  60-69      ge40  Tumor-size  15-19
3     no-recurrence-events  40-49   premeno  Tumor-size    0-4
4     no-recurrence-events  60-69      ge40  Tumor-size  15-19
...                    ...    ...       ...         ...    ...
1990     recurrence-events  30-39   premeno    Irradiat     no
1991     recurrence-events  30-39   premeno    Irradiat    yes
1992     recurrence-events  60-69      ge40    Irradiat     no
1993     recurrence-events  40-49      ge40    Irradiat     no
1994     recurrence-events  50-59      ge40    Irradiat     no

[1995 rows x 5 columns]

In [109]:
#Pivot
df1 = df.drop_duplicates(subset=['Menopause'])
df2 = df1.pivot(index= 'Menopause', columns='Age', values= 'Tumor-size')
df2

Age        40-49  60-69
Menopause
ge40         NaN  15-19
lt40         NaN  10-14
premeno    20-24    NaN

In [71]:
#Aggregation 
df.agg({ 'Age' : "count", 'Inv-nodes' : "max", 'Tumor-size' : "min"})

Age            285
Inv-nodes     9-11
Tumor-size     0-4
dtype: object

In [97]:
#Iteration
for index, row in df.iterrows():
    print(index, row['Menopause'])

0 premeno
1 premeno
2 ge40
3 premeno
4 ge40
5 premeno
6 ge40
7 premeno
8 premeno
9 premeno
10 ge40
11 lt40
12 ge40
13 premeno
14 lt40
15 premeno
16 premeno
17 ge40
18 ge40
19 ge40
20 ge40
21 premeno
22 premeno
23 premeno
24 premeno
25 premeno
26 ge40
27 premeno
28 ge40
29 ge40
30 premeno
31 premeno
32 ge40
33 ge40
34 premeno
35 ge40
36 ge40
37 premeno
38 premeno
39 ge40
40 ge40
41 ge40
42 premeno
43 ge40
44 ge40
45 premeno
46 premeno
47 premeno
48 premeno
49 lt40
50 premeno
51 premeno
52 ge40
53 ge40
54 ge40
55 ge40
56 ge40
57 ge40
58 ge40
59 premeno
60 premeno
61 ge40
62 premeno
63 premeno
64 premeno
65 premeno
66 ge40
67 ge40
68 ge40
69 ge40
70 premeno
71 ge40
72 premeno
73 premeno
74 ge40
75 ge40
76 premeno
77 premeno
78 premeno
79 ge40
80 ge40
81 ge40
82 ge40
83 premeno
84 ge40
85 ge40
86 ge40
87 ge40
88 premeno
89 premeno
90 ge40
91 ge40
92 ge40
93 premeno
94 premeno
95 ge40
96 ge40
97 premeno
98 premeno
99 ge40
100 ge40
101 premeno
102 premeno
103 premeno
104 premeno
105 premeno
106 premeno
107 premeno
108 ge40
109 ge40
110 ge40
111 premeno
112 premeno
113 premeno
114 ge40
115 premeno
116 ge40
117 premeno
118 ge40
119 ge40
120 ge40
121 ge40
122 ge40
123 ge40
124 ge40
125 premeno
126 premeno
127 premeno
128 premeno
129 premeno
130 premeno
131 premeno
132 ge40
133 ge40
134 premeno
135 premeno
136 premeno
137 premeno
138 premeno
139 ge40
140 premeno
141 ge40
142 premeno
143 ge40
144 premeno
145 ge40
146 premeno
147 premeno
148 lt40
149 ge40
150 ge40
151 ge40
152 ge40
153 lt40
154 ge40
155 ge40
156 premeno
157 ge40
158 premeno
159 premeno
160 premeno
161 ge40
162 ge40
163 ge40
164 premeno
165 premeno
166 ge40
167 premeno
168 ge40
169 premeno
170 premeno
171 ge40
172 ge40
173 premeno
174 premeno
175 ge40
176 ge40
177 premeno
178 premeno
179 premeno
180 premeno
181 premeno
182 ge40
183 ge40
184 premeno
185 ge40
186 ge40
187 premeno
188 ge40
189 premeno
190 premeno
191 ge40
192 premeno
193 premeno
194 ge40
195 premeno
196 premeno
197 ge40
198 premeno
199 ge40
200 premeno
201 premeno
202 ge40
203 premeno
204 premeno
205 ge40
206 premeno
207 premeno
208 premeno
209 premeno
210 ge40
211 premeno
212 premeno
213 ge40
214 ge40
215 ge40
216 premeno
217 ge40
218 premeno
219 premeno
220 premeno
221 ge40
222 ge40
223 premeno
224 ge40
225 premeno
226 premeno
227 ge40
228 ge40
229 premeno
230 premeno
231 premeno
232 ge40
233 ge40
234 premeno
235 premeno
236 premeno
237 premeno
238 premeno
239 ge40
240 premeno
241 ge40
242 ge40
243 premeno
244 premeno
245 premeno
246 ge40
247 ge40
248 premeno
249 premeno
250 premeno
251 premeno
252 ge40
253 premeno
254 premeno
255 premeno
256 premeno
257 ge40
258 ge40
259 ge40
260 ge40
261 ge40
262 lt40
263 lt40
264 premeno
265 premeno
266 ge40
267 premeno
268 premeno
269 ge40
270 premeno
271 premeno
272 ge40
273 ge40
274 premeno
275 premeno
276 ge40
277 premeno
278 ge40
279 ge40
280 premeno
281 premeno
282 ge40
283 ge40
284 ge40

In [95]:
#Groupby
df.groupby('Class', as_index=False).agg({'Age' : 'count', 'Deg-malig' : 'std'})

                  Class  Age  Deg-malig
0  no-recurrence-events  200   0.694559
1     recurrence-events   85   0.725293